In [2]:
import pandas as pd
data_url = 'https://andybek.com/pandas-nutrition'
df = pd.read_csv(data_url)
df

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8784,8784,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,125,3.5g,1.4g,62mg,54.00 mg,64.5 mg,4.00 mcg,...,3.50 g,1.353 g,1.554 g,0.244 g,62.00 mg,0.0 g,1.11 g,0.00 mg,0.00 mg,72.51 g
8785,8785,"Lamb, cooked, separable lean only, composite o...",100 g,206,8.9g,3.9g,109mg,50.00 mg,0,0.00 mcg,...,8.86 g,3.860 g,3.480 g,0.520 g,109.00 mg,0,1.60 g,0,0,59.95 g
8786,8786,"Lamb, raw, separable lean and fat, composite o...",100 g,277,23g,12g,78mg,39.00 mg,0,1.00 mcg,...,22.74 g,11.570 g,8.720 g,0.980 g,78.00 mg,0,0.92 g,0,0,59.80 g
8787,8787,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,121,3g,1.1g,60mg,53.00 mg,64.2 mg,4.00 mcg,...,3.04 g,1.086 g,1.266 g,0.233 g,60.00 mg,0.0 g,1.10 g,0.00 mg,0.00 mg,73.43 g
8788,8788,"Beef, raw, all grades, trimmed to 0"" fat, sepa...",100 g,121,3g,1.1g,60mg,53.00 mg,64.2 mg,4.00 mcg,...,3.04 g,1.086 g,1.266 g,0.233 g,60.00 mg,0.0 g,1.10 g,0.00 mg,0.00 mg,73.43 g

### 1. Get Random 10 row to new var nutri_mini

In [4]:
#random 10 row
nu_mini=df.sample(10)
nu_mini

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
7649,7649,"Beef, broiled, cooked, select, trimmed to 0"" f...",100 g,177,7.4g,2.8g,80mg,71.00 mg,99.0 mg,8.00 mcg,...,7.36 g,2.820 g,3.340 g,0.380 g,80.00 mg,0.0 g,1.20 g,0.00 mg,0.00 mg,63.73 g
1836,1836,"Alcoholic beverage, rice (sake)",100 g,134,0g,NaN,0,2.00 mg,0.0 mg,0.00 mcg,...,0.00 g,0.000 g,0.000 g,0.000 g,0.00 mg,16.1 g,0.00 g,0.00 mg,0.00 mg,78.40 g
1976,1976,"MOTHER'S, Iced Oatmeal Cookies",100 g,463,18g,5.8g,1mg,493.00 mg,0,60.00 mcg,...,18.00 g,5.800 g,4.200 g,6.700 g,1.00 mg,0,0,0,0,3.50 g
7127,7127,"Squash, without salt, drained, boiled, cooked,...",100 g,15,0.4g,0.1g,0,3.00 mg,9.4 mg,28.00 mcg,...,0.36 g,0.072 g,0.029 g,0.151 g,0.00 mg,0.0 g,0.59 g,0.00 mg,0.00 mg,95.22 g
6625,6625,"Cereals ready-to-eat, CAP'N CRUNCH'S PEANUT BU...",100 g,417,9.2g,3.9g,0,742.00 mg,14.7 mg,1554.00 mcg,...,9.23 g,3.920 g,2.641 g,2.148 g,0.00 mg,0.0 g,2.52 g,0.00 mg,0.00 mg,2.50 g
8082,8082,"Pork, roasted, cooked, separable lean only, bo...",100 g,214,10g,3.5g,83mg,50.00 mg,0,9.00 mcg,...,10.13 g,3.540 g,4.490 g,0.850 g,83.00 mg,0,1.14 g,0,0,60.61 g
8001,8001,"Infant formula, with ARA and DHA, ready-to-fee...",100 g,64,3.5g,1.5g,1mg,18.00 mg,8.0 mg,11.00 mcg,...,3.50 g,1.453 g,1.255 g,0.670 g,1.00 mg,0.0 g,0.32 g,0.00 mg,0.00 mg,88.35 g
1816,1816,"Emu, broiled, cooked, full rump",100 g,168,2.7g,0.9g,129mg,110.00 mg,0,10.00 mcg,...,2.68 g,0.870 g,1.079 g,0.613 g,129.00 mg,0.0 g,1.35 g,0.00 mg,0.00 mg,61.97 g
8669,8669,"Beef, raw, select, trimmed to 1/8"" fat, separa...",100 g,179,11g,3.9g,68mg,78.00 mg,0,3.00 mcg,...,10.90 g,3.930 g,5.626 g,0.366 g,68.00 mg,0.0 g,0.90 g,0.00 mg,0.00 mg,68.60 g
40,40,"Gravy, mix, dry, onion",100 g,322,3g,1.9g,2mg,4186.00 mg,0,31.00 mcg,...,3.00 g,1.860 g,0.900 g,0.140 g,2.00 mg,0,16.00 g,0,0,4.36 g

### 2. Extract total_fat and cholestrol form the nu_mini var

In [7]:
nu_mini.loc[:, ['total_fat','cholesterol']]

     total_fat cholesterol
7649      7.4g        80mg
1836        0g           0
1976       18g         1mg
7127      0.4g           0
6625      9.2g           0
8082       10g        83mg
8001      3.5g         1mg
1816      2.7g       129mg
8669       11g        68mg
40          3g         2mg

### 3. Extract all colm from vitamin_b12 to end, for 1st, 2nd and 3rd row

In [8]:
nu_mini.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 7649 to 40
Data columns (total 77 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   10 non-null     int64
 1   name                         10 non-null     object
 2   serving_size                 10 non-null     object
 3   calories                     10 non-null     int64
 4   total_fat                    10 non-null     object
 5   saturated_fat                9 non-null      object
 6   cholesterol                  10 non-null     object
 7   sodium                       10 non-null     object
 8   choline                      10 non-null     object
 9   folate                       10 non-null     object
 10  folic_acid                   10 non-null     object
 11  niacin                       10 non-null     object
 12  pantothenic_acid             10 non-null     object
 13  riboflavin                   10 non-null     object
 14  thiamin                      10 non-null     object
 15  vitamin_a                    10 non-null     object
 16  vitamin_a_rae                10 non-null     object
 17  carotene_alpha               10 non-null     object
 18  carotene_beta                10 non-null     object
 19  cryptoxanthin_beta           10 non-null     object
 20  lutein_zeaxanthin            10 non-null     object
 21  lucopene                     10 non-null     int64
 22  vitamin_b12                  10 non-null     object
 23  vitamin_b6                   10 non-null     object
 24  vitamin_c                    10 non-null     object
 25  vitamin_d                    10 non-null     object
 26  vitamin_e                    10 non-null     object
 27  tocopherol_alpha             10 non-null     object
 28  vitamin_k                    10 non-null     object
 29  calcium                      10 non-null     object
 30  copper                       10 non-null     object
 31  irom                         10 non-null     object
 32  magnesium                    10 non-null     object
 33  manganese                    10 non-null     object
 34  phosphorous                  10 non-null     object
 35  potassium                    10 non-null     object
 36  selenium                     10 non-null     object
 37  zink                         10 non-null     object
 38  protein                      10 non-null     object
 39  alanine                      10 non-null     object
 40  arginine                     10 non-null     object
 41  aspartic_acid                10 non-null     object
 42  cystine                      10 non-null     object
 43  glutamic_acid                10 non-null     object
 44  glycine                      10 non-null     object
 45  histidine                    10 non-null     object
 46  hydroxyproline               10 non-null     object
 47  isoleucine                   10 non-null     object
 48  leucine                      10 non-null     object
 49  lysine                       10 non-null     object
 50  methionine                   10 non-null     object
 51  phenylalanine                10 non-null     object
 52  proline                      10 non-null     object
 53  serine                       10 non-null     object
 54  threonine                    10 non-null     object
 55  tryptophan                   10 non-null     object
 56  tyrosine                     10 non-null     object
 57  valine                       10 non-null     object
 58  carbohydrate                 10 non-null     object
 59  fiber                        10 non-null     object
 60  sugars                       10 non-null     object
 61  fructose                     10 non-null     object
 62  galactose                    10 non-null     object
 63  glucose                      10 non-null     object
 64  lactose                      10 non-null     object
 65  maltose                      10 non-null     object
 66  sucrose                      10 non-null     object
 67  fat                          10 non-null     object
 68  saturated_fatty_acids        10 non-null     object
 69  monounsaturated_fatty_acids  10 non-null     object
 70  polyunsaturated_fatty_acids  10 non-null     object
 71  fatty_acids_total_trans      10 non-null     object
 72  alcohol                      10 non-null     object
 73  ash                          10 non-null     object
 74  caffeine                     10 non-null     object
 75  theobromine                  10 non-null     object
 76  water                        10 non-null     object
dtypes: int64(3), object(74)
memory usage: 6.1+ KB

In [13]:
nu_mini.iloc[0:3, 22:]

,vitamin_b12,vitamin_b6,vitamin_c,vitamin_d,vitamin_e,tocopherol_alpha,vitamin_k,calcium,copper,irom,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
7649,2.27 mcg,0.390 mg,0.0 mg,0,0.14 mg,0.14 mg,0,4.00 mg,0.143 mg,3.66 mg,...,7.36 g,2.820 g,3.340 g,0.380 g,80.00 mg,0.0 g,1.20 g,0.00 mg,0.00 mg,63.73 g
1836,0.00 mcg,0.000 mg,0.0 mg,0.00 IU,0.00 mg,0.00 mg,0.0 mcg,5.00 mg,0.009 mg,0.10 mg,...,0.00 g,0.000 g,0.000 g,0.000 g,0.00 mg,16.1 g,0.00 g,0.00 mg,0.00 mg,78.40 g
1976,0,0.010 mg,0,0,0,0,0,0,0,2.30 mg,...,18.00 g,5.800 g,4.200 g,6.700 g,1.00 mg,0,0,0,0,3.50 g

### 4. Get calories for 3rd food in nu_mini

In [14]:
nu_mini.iloc[2,3]

np.int64(463)